// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQs3CBJOCpDtebCUjf0CR2S0vuZBGCFxw',
    appId: '1:621547872493:web:1b422ea80454033452ace4',
    messagingSenderId: '621547872493',
    projectId: 'fir-f303d',
    authDomain: 'fir-f303d.firebaseapp.com',
    storageBucket: 'fir-f303d.appspot.com',
    measurementId: 'G-YMCXKXCBP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtMeRWpEZR7NA28n9e7rKurBNeKcDI5NE',
    appId: '1:621547872493:android:0f314f9db86d1d3e52ace4',
    messagingSenderId: '621547872493',
    projectId: 'fir-f303d',
    storageBucket: 'fir-f303d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBppRh3qCcppnvKB2DH6sgZ1UXjmm0wJSE',
    appId: '1:621547872493:ios:c1a9dd06e613cdfb52ace4',
    messagingSenderId: '621547872493',
    projectId: 'fir-f303d',
    storageBucket: 'fir-f303d.appspot.com',
    androidClientId: '621547872493-bk572abath1nf6dfn7l1t857henpcj1u.apps.googleusercontent.com',
    iosClientId: '621547872493-7k1c9v30t1u24d18olovgsubp5keomij.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
